### ISSUE TITLE
Html engine is always rendering the wrong file

### ISSUE THREAD

**Issue by buroz** [gofiber/template#149]
I don't quite understand where I went wrong, but it seems quite logical to me. I made a simple copy for you to see, I am sharing the link below. Can someone help me with where I went wrong? 

[Example Repo](https://github.com/buroz/fiber-issue)

**Comment by ansidev** [comment]
@buroz This is a bad question, nobody will guess your detail problem(s). You should provide what was wrong and your expectation.

**Comment by buroz** [comment]
If you had read the repo, you could see that there are two routes defined. One should to render views/pages/home.html and the other a views/pages/place.html, but I see the views/pages/place.html for both routes. Actually, it is very simple, I think you are talking without understanding the problem. You could understand the situation simply by reading the main.go file. There was no need for unnecessary aggression.

**Comment by ReneWerner87** [comment]
i'll look up right now, @ansidev is already right, you should always break down the problem in the description of the issue, your example repository is good for checking the problem, but unfortunately can always change

but the issue is there so that others know about the solution or can find the error in their system directly here
-> without describing the exact problem, everyone would have to go through all the issues and call all the links everywhere to understand the complete problem and check if he has the same occurrence

it is quite complicated with an external repository, which can be changed at any time.

**Comment by ReneWerner87** [comment]
@buroz 
okay see the problem

you have built your own layout system, although we offer this possibility with the {{embed}} placeholder and the layout specification, where you specify where the content of the template you are running should be rendered in

please check the basic example with the layout: https://github.com/gofiber/template/tree/master/html#basic-example

---
problem with your variant with the define blocks is that the identifiers of these are not unique

because before using the template engine everything is parsed and added to the go template engine, later when calling the render method only the template is picked out which should be rendered, but here exist several blocks with the same name and the base file doesn't know which one it should take

in my test the base file uses e.g. the define block from the place file although i specified the home file for rendering, probably this is because the other file was added sooner or later in the pre-rendering process by the go template system and then overwrites the block

**Comment by ospng** [comment]
> @buroz okay see the problem
> 
> you have built your own layout system, although we offer this possibility with the {{embed}} placeholder and the layout specification, where you specify where the content of the template you are running should be rendered in
> 
> please check the basic example with the layout: https://github.com/gofiber/template/tree/master/html#basic-example
> 
> problem with your variant with the define blocks is that the identifiers of these are not unique
> 
> because before using the template engine everything is parsed and added to the go template engine, later when calling the render method only the template is picked out which should be rendered, but here exist several blocks with the same name and the base file doesn't know which one it should take
> 
> in my test the base file uses e.g. the define block from the place file although i specified the home file for rendering, probably this is because the other file was added sooner or later in the pre-rendering process by the go template system and then overwrites the block
> 
> here some infos about the go template system https://github.com/gofiber/template/blob/master/html/TEMPLATES_CHEATCHEET.md

Hi, what if I want to render different css files from user.html and product.html using the same layout.html? 

The {{embed}} I used is for body rendering.

When I use {{template "css" .}} in layout.html,  and then use {{define "css"}} {{end}} separately in user.html and product.html, the last one overrides previous ones according to the order of parsing files, which leads to loading css file.

How can I fix this? 

Thanks.
