### ISSUE TITLE
Render not pass variable if set fiber.Map

### ISSUE THREAD

**Issue by vmpartner** [gofiber/template#23]
I am use Jet template

This not work:
```golang
		err := c.Render("index", fiber.Map{
			"qwe": "Hello, World 👋!",
		})
```

This work:
```golang
		err := c.Render("index", map[string]interface{}{
			"qwe": "Hello, World 👋!",
		})
```

**Comment by huyhvq** [comment]
because in func `jetVarMap ` https://github.com/gofiber/template/blob/d8ce3c24f0faa103f22f2a55f372efa89a71c017/jet/jet.go#L211-L225
doesn't check type `fiber.Map` so we can fix with:
```
if binds, ok := binding.(fiber.Map); ok {
//do something
}
```
but it must import pkg "github.com/gofiber/fiber"

or we can fix it in:
convert bind to map[string]interface
https://github.com/gofiber/fiber/blob/b5645f8f21b159120f4c84dfefe8b5b2327cc5c5/ctx.go#L770

**Comment by fuadarradhi** [comment]
i just change this line to `func (ctx *Ctx) Render(name string, bind map[string]interface{}, layouts ...string) (err error) {`
look ok for now

https://github.com/gofiber/fiber/blob/b5645f8f21b159120f4c84dfefe8b5b2327cc5c5/ctx.go#L756

**Comment by Fenny** [comment]
That would do the trick, I can accept a PR with this fix 👍

**Comment by Fenny** [comment]
Fixed in https://github.com/gofiber/template/pull/27

**Comment by fuadarradhi** [comment]
@Fenny , another template need this patch too

**Comment by Fenny** [comment]
@fuadarradhi, which one?

**Comment by fuadarradhi** [comment]
@Fenny, django/pongo2 template.

https://github.com/gofiber/template/blob/master/django/django.go#L180-L182

**Comment by Fenny** [comment]
Did you test this? `fiber.Map` = `map[string]interface{}`

**Comment by Fenny** [comment]
Should be fixed in <https://github.com/gofiber/template/releases/tag/v1.5.5> thnx for the report 👍
