### ISSUE TITLE
"wrong number of args" when using AddFunc

### ISSUE THREAD

**Issue by aep** [gofiber/template#77]
is there an example how to use functions passed with AddFunc in html templates?

this works only when the function is passed in via c.Render("", fiber.Map{"Static": ...   but not with AddFunc

```
{{ call Static "bla" }}
```

```
 | template: layout:8:45: executing "layout" at <Static>: wrong number of args for Static: want 1 got 0
```

**Comment by ReneWerner87** [comment]
sorry for the late reply, can you give me a specific case, then i will test it

everything should work the same as with the normal use of golang html/template

this library is just a wrapper around the functionality so that this can be better integrated into the fiber world
https://golang.org/pkg/html/template/

**Comment by ReneWerner87** [comment]
Since there is no further message, I assume that the issue is done and can be closed.

if you have any questions, please feel free to open the issue again
